# Generated by Django 5.1.2 on 2024-11-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_remove_itineraryactivity_activity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination",
            name="city",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="longitude",
        ),
        migrations.AddField(
            model_name="destination",
            name="currency",
            field=models.CharField(default="none", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="destination",
            name="language",
            field=models.CharField(default="none", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="destination",
            name="timezone",
            field=models.CharField(default="none", max_length=10),
            preserve_default=False,
        ),
    ]
