# Generated by Django 5.1.3 on 2024-12-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_destination_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
