# Generated by Django 5.1.3 on 2024-12-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_destination_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
